export const PERMISSIONS = {
  SUPPLIER_READ: 'supplier:read',
  SUPPLIER_WRITE: 'supplier:write',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  SHIPMENT_READ: 'shipment:read',
  SHIPMENT_WRITE: 'shipment:write',
  SHIPMENT_RECEIVE: 'shipment:receive',
  PURCHASE_ORDER_READ: 'purchase-order:read',
  PURCHASE_ORDER_WRITE: 'purchase-order:write',
  PURCHASE_ORDER_APPROVE: 'purchase-order:approve',
  PURCHASE_ORDER_RECEIVE: 'purchase-order:receive',
  DASHBOARD_READ: 'dashboard:read',
  AUDIT_READ: 'audit:read',
  USER_MANAGE: 'user:manage',
} as const;
